### Initialization

In [1]:
from os import chdir
import numpy as np
import pandas as pd
import networkx as nx
import pickle

In [2]:
chdir('Library/')

### Degree Features

In [3]:
execfile('degree.py')

Fitting Degree Feature Graph
Fitting Logistic Regression
[LibLinear]Accuracy 0.748639984457
F1 0.749625042334


In [4]:
unique, counts = np.unique(YTEST, return_counts=True)
print np.asarray((unique, counts)).T

[[   -1 10340]
 [    1 10248]]


In [5]:
unique, counts = np.unique(PTEST, return_counts=True)
print np.asarray((unique, counts)).T

[[   -1 10167]
 [    1 10421]]


### Triad Features

In [6]:
execfile('triad.py')

Fitting Triad Feature Graph
Fitting Logistic Regression
[LibLinear]Accuracy 0.683456382359
F1 0.636875243773


In [7]:
unique, counts = np.unique(YTEST, return_counts=True)
print np.asarray((unique, counts)).T

[[   -1 10220]
 [    1 10368]]


In [8]:
unique, counts = np.unique(PTEST, return_counts=True)
print np.asarray((unique, counts)).T

[[   -1 13009]
 [    1  7579]]


### Degree & Triad Features

In [9]:
execfile('degree_triad.py')

Fitting Degree Feature Graph
Fitting Triad Feature Graph
Fitting Logistic Regression
[LibLinear]Accuracy 0.752040023315
F1 0.755613002058


In [10]:
unique, counts = np.unique(YTEST, return_counts=True)
print np.asarray((unique, counts)).T

[[   -1 10180]
 [    1 10408]]


In [11]:
unique, counts = np.unique(PTEST, return_counts=True)
print np.asarray((unique, counts)).T

[[   -1 10107]
 [    1 10481]]


### Graph Analysis

In [12]:
# df = pickle.load(open("../wikipedia_admin/edges_df.p", "rb"))

# graph = nx.from_pandas_dataframe(df,
#                                       'SRC', 'TGT', 
#                                       'RES',
#                                       nx.DiGraph())    

# data_pos = df.ix[df.VOT == 1, :].reset_index(drop=True)
# data_neg = df.ix[df.VOT == -1, :].reset_index(drop=True)

In [13]:
# print 'Proportion of negative edges : %.2f%% (%d edges)' %(100*float(len(data_neg))/(len(data_neg)+len(data_pos)), len(data_neg))

In [14]:
[0]*16

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]